export const rnTokens = {
  color: {
    shellYellow: "#F6D246",
    shellYellowDeep: "#E8BE26",
    paper: "#FFF9EB",
    paperWarm: "#FFF4D8",
    paperShadow: "rgba(43, 35, 20, 0.18)",
    ink: "#171717",
    inkSoft: "#3A3427",
    muted: "#8A8070",
    divider: "rgba(23, 23, 23, 0.12)",
    agentBubble: "#FFF9EA",
    userBubbleTop: "#F9D84D",
    userBubbleBottom: "#F5C93A",
    cardHeader: "#F5D35A",
    cardBody: "#FFF7E6",
    settingsPanel: "#FFF8E8",
    backdrop: "rgba(17, 17, 17, 0.24)",
    info: "#4B8FD8",
    warning: "#E59A2D",
    danger: "#B83A4B",
    disabled: "#D8D0BE",
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 28,
    screenX: 10,
    paperInsetTop: 34,
    paperInsetRight: 22,
    paperInsetBottom: 28,
    paperInsetLeft: 22,
    composerHeightMin: 48,
    composerHeightMax: 108,
  },
  radius: {
    bubble: 17,
    bubbleTail: 6,
    card: 14,
    composer: 24,
    buttonRound: 999,
    drawer: 18,
    menu: 14,
  },
  stroke: {
    hairline: 1,
    thin: 1.5,
    regular: 2,
    bold: 2.6,
    frame: 4,
  },
  type: {
    displayWeight: "900" as const,
    bodyWeight: "500" as const,
    strongWeight: "800" as const,
    captionWeight: "600" as const,
    sizes: {
      caption: 11,
      meta: 12,
      body: 15,
      bodyLarge: 16,
      cardTitle: 18,
      screenTitle: 24,
    },
    lineHeights: {
      caption: 16,
      meta: 18,
      body: 23,
      bodyLarge: 25,
      cardTitle: 24,
    },
  },
  motion: {
    fastMs: 120,
    normalMs: 180,
    drawerMs: 220,
    longPressMs: 430,
  },
  shadow: {
    bubble: {
      ios: {
        shadowColor: "#111111",
        shadowOffset: { height: 3, width: 0 },
        shadowOpacity: 0.14,
        shadowRadius: 0,
      },
      androidElevation: 2,
    },
    card: {
      ios: {
        shadowColor: "#111111",
        shadowOffset: { height: 5, width: 0 },
        shadowOpacity: 0.16,
        shadowRadius: 0,
      },
      androidElevation: 3,
    },
    drawer: {
      ios: {
        shadowColor: "#111111",
        shadowOffset: { height: 0, width: -8 },
        shadowOpacity: 0.22,
        shadowRadius: 16,
      },
      androidElevation: 8,
    },
  },
  breakpoints: {
    baseWidth: 390,
  },
} as const;
